### ISSUE TITLE
Add Timer on Every Step and Substep

### ISSUE THREAD

**Issue by solvingj** [karfunkel/glow#1]
In most workflow scenarios, tracking performance and time spent during operations becomes a key metric. Seems good to have it on the roadmap.

**Comment by karfunkel** [comment]
Each step now has a property $info containing a Map of Maps per step-closure (or a List of Maps if the closure has been executed multiple times) with a java.util.Date for 'start' and 'end' and the 'duration' in ms.
onError has 'exception' containing the thrown exception.
